### ISSUE TITLE
碰到的几个问题。。

### ISSUE THREAD

**Issue by tommyyang21** [EAFFGH/Douban-to-Trakt#1]
感谢作者的工作，最近正好想使用trakt，发现这个工具，因为不懂编程，花了两个晚上，参考了python入门的基础教程，总算是成功，以下是几个碰到的问题

首次运行re-xlsx.py出错：
FileNotFoundError: [Errno 2] No such file or directory: 'douban-alter.xlsx'
将使用方法第二条里的文件名改为 'douban-alter.xlsx'后成功

运行re-xlsx.py不到一半出错：
  File "re-xlsx.py", line 30, in <module>
    print('error_code: '+url_page.status_code)
TypeError: can only concatenate str (not "int") to str
根据搜索错误信息将‘re-xlsx.py’文件内这一段
`print('error_code: '+url_page.status_code)` 改为 `print(int('error_code: ')+url_page.status_code)` 不成功
改为 `print('error_code: ' + str(url_page.status_code))` 成功运行

**Comment by EAFFGH** [comment]
多谢反馈，我去修改验证下
